In [1]:
from pathlib import Path
import pandas as pd

**Running the other notebook in this one to call the functions here**

In [2]:
%run helper_functions.ipynb

**Specifying paths and names**

In [13]:
path = Path('./data') # path to data directory
season_paths= [path/'2016-17',path/'2017-18',path/'2018-19',path/'2019-20'] # paths to each season's data
season_names=['1617','1718','1819','1920'] # names for each season
teams = pd.read_csv(path/'teams.csv') #team codes

**All Players DataFrame**

In [4]:
all_players = build_players(path, season_paths, season_names, teams)

In [5]:
all_players.head(10)

,full_name,bps_1617,play_proba_1617,position_1617,id_1617,cost_1617,selected_by_percent_1617,team_1617,transfers_in_1617,transfers_in_event_1617,...,play_proba_1920,position_1920,id_1920,cost_1920,selected_by_percent_1920,team_1920,transfers_in_1920,transfers_in_event_1920,transfers_out_1920,transfers_out_event_1920
0,David_Ospina,18.0,100,1.0,1.0,47.0,0.2,3.0,3433.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Petr_Cech,660.0,100,1.0,2.0,54.0,13.7,3.0,432837.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Laurent_Koscielny,723.0,0,2.0,3.0,61.0,11.2,3.0,965040.0,0.0,...,0,2.0,7.0,50.0,0.1,3.0,740.0,7.0,12867.0,10.0
3,Per_Mertesacker,5.0,100,2.0,4.0,48.0,0.2,3.0,2141.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gabriel Armando_de Abreu,296.0,75,2.0,5.0,48.0,0.8,3.0,119600.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Héctor_Bellerín,569.0,100,2.0,6.0,65.0,13.9,3.0,403777.0,0.0,...,100,2.0,2.0,53.0,1.0,3.0,198157.0,791.0,149413.0,1991.0
6,Kieran_Gibbs,201.0,75,2.0,7.0,47.0,1.7,3.0,70359.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Mathieu_Debuchy,2.0,100,2.0,8.0,46.0,0.2,3.0,2211.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Carl_Jenkinson,12.0,100,2.0,9.0,48.0,0.1,3.0,9727.0,0.0,...,0,2.0,9.0,45.0,0.0,3.0,492.0,4.0,2682.0,5.0
9,Nacho_Monreal,681.0,100,2.0,10.0,59.0,6.4,3.0,299355.0,0.0,...,0,2.0,6.0,50.0,0.2,3.0,28241.0,7.0,89250.0,18.0

In [6]:
all_players.columns

Index(['full_name', 'bps_1617', 'play_proba_1617', 'position_1617', 'id_1617',
       'cost_1617', 'selected_by_percent_1617', 'team_1617',
       'transfers_in_1617', 'transfers_in_event_1617', 'transfers_out_1617',
       'transfers_out_event_1617', 'bps_1718', 'play_proba_1718',
       'position_1718', 'id_1718', 'cost_1718', 'selected_by_percent_1718',
       'team_1718', 'transfers_in_1718', 'transfers_in_event_1718',
       'transfers_out_1718', 'transfers_out_event_1718', 'bps_1819',
       'play_proba_1819', 'position_1819', 'id_1819', 'cost_1819',
       'selected_by_percent_1819', 'team_1819', 'transfers_in_1819',
       'transfers_in_event_1819', 'transfers_out_1819',
       'transfers_out_event_1819', 'bps_1920', 'play_proba_1920',
       'position_1920', 'id_1920', 'cost_1920', 'selected_by_percent_1920',
       'team_1920', 'transfers_in_1920', 'transfers_in_event_1920',
       'transfers_out_1920', 'transfers_out_event_1920'],
      dtype='object')

**Build Season DataFrame for 16/17 season**

In [7]:
df_1617 = build_season(season_paths[0], season_names[0], teams, all_players, gw = range(1,39))
# df_1617.to_csv('1617 season all player data.csv')

**Build Season DataFrame for 17/18 season**

In [8]:
df_1718 = build_season(season_paths[1], season_names[1], teams, all_players, gw = range(1,39))
# df_1718.to_csv('1718 season all player data.csv')

**Build Season DataFrame for 18/19 season**

In [9]:
df_1819 = build_season(season_paths[2], season_names[2], teams, all_players, gw = range(1,39))
# df_1819.to_csv('1819 season all player data.csv')

**Building DF with Data for current 19/20 season**

In [10]:
df_1920 = build_season(season_paths[3], season_names[3], teams, all_players, gw = range(1,30))
# df_1920.to_csv('1920 season all player data.csv')

**Labelling player positions**

In [11]:
label_player_positions(df_1617)
label_player_positions(df_1718)
label_player_positions(df_1819)
label_player_positions(df_1920)

,player,gw,minutes,team,position,position_name,opponent_team,was_home,total_points,assists,...,selected,team_a_score,team_h_score,threat,transfers_balance,transfers_in,transfers_out,yellow_cards,kickoff_time,season
0,Aaron_Cresswell,1,90,West Ham United,2,DEF,Manchester City,True,0,0,...,23399,5.0,0.0,0.0,0,0,0,0,2019-08-10T11:30:00Z,1920
1,Aaron_Lennon,1,6,Burnley,3,MID,Southampton,True,1,0,...,8105,0.0,3.0,0.0,0,0,0,0,2019-08-10T14:00:00Z,1920
2,Aaron_Mooy,1,0,Brighton and Hove Albion,3,MID,Watford,False,0,0,...,16261,3.0,0.0,0.0,0,0,0,0,2019-08-10T14:00:00Z,1920
3,Aaron_Ramsdale,1,90,Bournemouth,1,GK,Sheffield United,True,2,0,...,3091,1.0,1.0,0.0,0,0,0,0,2019-08-10T14:00:00Z,1920
4,Aaron_Wan-Bissaka,1,90,Manchester United,2,DEF,Chelsea,True,8,0,...,1879259,0.0,4.0,2.0,0,0,0,0,2019-08-11T15:30:00Z,1920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16580,Jack_Simpson,29,71,Bournemouth,2,DEF,Liverpool,False,1,0,...,509248,1.0,2.0,0.0,-7402,2014,9416,0,2020-03-07T12:30:00Z,1920
16581,Miguel_Almirón,29,90,Newcastle United,3,MID,Southampton,False,3,0,...,56161,1.0,0.0,54.0,11,5469,5458,0,2020-03-07T15:00:00Z,1920
16582,Jack_O'Connell,29,90,Sheffield United,2,DEF,Norwich,True,6,0,...,262444,0.0,1.0,24.0,5397,16521,11124,0,2020-03-07T15:00:00Z,1920
16583,Luka_Milivojevic,29,20,Crystal Palace,3,MID,Watford,True,1,0,...,140638,0.0,1.0,0.0,-613,487,1100,0,2020-03-07T15:00:00Z,1920
16584,Çaglar_Söyüncü,29,90,Leicester City,2,DEF,Aston Villa,True,6,0,...,1184951,0.0,4.0,6.0,-28582,25649,54231,0,2020-03-09T20:00:00Z,1920

**Concatenating all the season DataFrame**

In [12]:
all_season_df = pd.concat([df_1617, df_1718, df_1819,df_1920], ignore_index = True, axis = 0,sort=False)